apiVersion: v2
name: isolation-templates
description: Smart defaults for isolations including Network Policies and Limit Ranges
home: https://loft.sh
icon: https://static.devspace.cloud/charts/logo-isolation-templates.svg
sources:
- https://github.com/loft-sh/isolation-templates
keywords:
- developer
- development
- sharing
- share
- multi-tenancy
- tenancy
- cluster
- space
- namespace
maintainers:
- name: DevSpace Technologies Inc.
  email: info@devspace.cloud
  url: https://twitter.com/DevSpace

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

version: 0.0.1 # version is auto-generated by release pipeline
