apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: allow-internet
resources:
  manifests:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-access-to-internet
      spec:
        podSelector: {}
        egress:
        - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
        policyTypes:
        - Egress
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-access-from-internet-via-label
      spec:
        podSelector:
          matchLabels:
            loft.sh/allow-access-from-internet: "true"
        ingress:
        - {}
        policyTypes:
        - Ingress

