apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: network-deny-default
resources:
  manifests:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: deny-default
      spec:
        podSelector: {}
        policyTypes:
          - Ingress
          - Egress
