style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/loft-sh/isolation-templates
options:
  commits:
#    filters:
#      Type:
#        - feat
#        - fix
#        - perf
#        - refactor
#        - docs
  commit_groups:
    title_maps:
      feat: 🚀 New Features
      fix: 🐛 Bug Fixes
      perf: 🏃‍♀️ Performance Improvements
      chart: 📊 Helm Chart
      refactor: 💡 Code Refactoring
      style: 💅 Code Style & Formatting
      test: 🧪 Tests Added/Fixed
      build: 🧱 Build Process Changes
      ci: 🤖 Changes to CI/CD
  header:
    pattern: "(?i)^(?:((?:feat)|(?:fix)|(?:perf)|(?:refactor)|(?:style)|(?:test)|(?:docs)|(?:build)|(?:ci)|)(?:(?:(?:[^):]*)\\()?([^)]*)\\)?)?:)?(.+)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  merges:
    pattern: "(?i)^Merges?(?: branch ')?(.+?)'?$"
    pattern_maps:
      - Source
  reverts:
    pattern: "(?i)^Reverts?(?: \")?(.+?)(?:\")?$"
    pattern_maps:
      - Header
  notes:
    keywords:
      - BREAKING CHANGE
      - "!"
