apiVersion: config.kiosk.sh/v1alpha1
kind: Template
metadata:
  name: container-default-resources
resources:
  manifests:
    - apiVersion: v1
      kind: LimitRange
      metadata:
        name: memory-limit-1gi
      spec:
        limits:
        - type: Container
          default:
            memory: 256Mi
            cpu: 200m
          defaultRequest:
            memory: 64Mi
            cpu: 20m
          min:
            memory: 64Mi
            cpu: 20m
